VERSION_MAJOR = 0
VERSION_MINOR = 1
VERSION_BUILD = 0
VERSION_ALPHA = 0

__version__ = (
    f"{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_BUILD}"
    if not VERSION_ALPHA
    else f"{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_BUILD}a{VERSION_ALPHA}"
)
